apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ionos-exporter.fullname" . }}
  labels:
    {{- include "ionos-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ionos-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ionos-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ionos-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          args:
            - "-config=/etc/ionos-exporter/config.yaml"
          livenessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{ if .Values.ionos.s3.enabled -}}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ionos.credentials.secret_name }}
                  key: {{ .Values.ionos.s3.credentials.access_key }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ionos.credentials.secret_name }}
                  key: {{ .Values.ionos.s3.credentials.secret_key }}
          {{ end -}}
            - name: IONOS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ionos.credentials.secret_name }}
                  key: {{ .Values.ionos.credentials.username_key }}
            - name: IONOS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ionos.credentials.secret_name  }}
                  key: {{ .Values.ionos.credentials.password_key  }}
            - name: IONOS_EXPORTER_S3_ENABLED
              value: {{ .Values.ionos.s3.enabled }}
            - name: IONOS_EXPORTER_APPLICATION_CONTAINER_PORT
              value: {{ .Values.containerPort | quote }}
            - name: IONOS_EXPORTER_API_CYCLE
              value: {{ .Values.ionosApiCycle | quote }}
          volumeMounts:
            - name: config-volume
              readOnly: true
              mountPath: /etc/ionos-exporter/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap: 
            name: ionos-exporter-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
