# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  build_image_on_push:
    uses: ./.github/workflows/imagetoghcr-on-push.yaml
    with:
      image_name: "ionos-exporter"
      context: "."
